### ISSUE TITLE
Možno oddati formo (submit) brez izpolniti vseh polj! [Serious]

### ISSUE THREAD

**Issue by AnzeSinigoj** [mit72/obrazec#1]
Praznemu polju izbrišeš atribut **required** s pomočjo inspect element in tako polje ni več obvezno ter lahko oddaš nepopolno formo.

**Comment by mit72** [comment]
> Praznemu polju izbrišeš atribut **required** s pomočjo inspect element in tako polje ni več obvezno ter lahko oddaš nepopolno formo.

To že vem, ne bom popravil, ker ni treba. Hvala za povratne informacije.
